// frontend/src/components/AddOrgObForm.jsx
import { useState, useEffect, useRef } from 'react'

const INPUT = 'bg-neutral-800 border border-neutral-600 rounded-lg px-3 py-2 text-sm text-white placeholder-neutral-500 focus:outline-none focus:border-indigo-500 w-full'

export default function AddOrgObForm({ onSubmit, onCancel }) {
  const [name, setName] = useState('')
  const [description, setDescription] = useState('')
  const inputRef = useRef(null)

  useEffect(() => { inputRef.current?.focus() }, [])

  function submit() {
    if (!name.trim()) return
    onSubmit({ name: name.trim(), description: description.trim() || null })
    setName('')
    setDescription('')
  }

  function handleKey(e) {
    if (e.key === 'Enter') { e.preventDefault(); submit() }
    if (e.key === 'Escape') { e.preventDefault(); onCancel() }
  }

  return (
    <div className="mt-3 flex flex-col gap-2">
      <input ref={inputRef} value={name} onChange={e => setName(e.target.value)}
        type="text" placeholder="Name" maxLength={200}
        className={INPUT} onKeyDown={handleKey} />
      <input value={description} onChange={e => setDescription(e.target.value)}
        type="text" placeholder="Description (optional)"
        className={INPUT} onKeyDown={handleKey} />
      <div className="flex gap-2">
        <button onClick={submit} disabled={!name.trim()}
          className="flex-1 py-1 px-3 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg text-xs disabled:opacity-40">
          Add
        </button>
        <button onClick={onCancel}
          className="py-1 px-3 bg-neutral-700 hover:bg-neutral-600 text-white rounded-lg text-xs">
          Cancel
        </button>
      </div>
    </div>
  )
}

// frontend/src/components/AddOrgObForm.vue
<template>
  <div class="mt-3 flex flex-col gap-2">
    <input
      v-model="name"
      type="text"
      placeholder="Name"
      maxlength="200"
      class="bg-dark-300 border border-gray-600 rounded-lg px-3 py-2 text-sm text-white placeholder-gray-500 focus:outline-none focus:border-primary-500 w-full"
      @keydown.enter.prevent="submit"
      @keydown.escape.prevent="$emit('cancel')"
      ref="inputRef"
    />
    <input
      v-model="description"
      type="text"
      placeholder="Description (optional)"
      class="bg-dark-300 border border-gray-600 rounded-lg px-3 py-2 text-sm text-white placeholder-gray-500 focus:outline-none focus:border-primary-500 w-full"
      @keydown.enter.prevent="submit"
      @keydown.escape.prevent="$emit('cancel')"
    />
    <div class="flex gap-2">
      <button
        @click="submit"
        :disabled="!name.trim()"
        class="btn btn-primary text-xs py-1 px-3 flex-1 disabled:opacity-40"
      >
        Add
      </button>
      <button
        @click="$emit('cancel')"
        class="btn btn-secondary text-xs py-1 px-3"
      >
        Cancel
      </button>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'

const emit = defineEmits(['submit', 'cancel'])

const name = ref('')
const description = ref('')
const inputRef = ref(null)

onMounted(() => {
  inputRef.value?.focus()
})

function submit() {
  if (!name.value.trim()) return
  emit('submit', { name: name.value.trim(), description: description.value.trim() || null })
  name.value = ''
  description.value = ''
}
</script>
